env:
  global:
    - CC_TEST_REPORTER_ID=<5a53fae00b4287ad7105026d6c625abc6db2274e1d33816b16d051221b3e323e>

rvm: '2.5.0'
cache: bundler

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle install && bin/rails db:create && bin/rails db:migrate && bundle exec rspec

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

services:
  — postgresql

deploy:
  provider: heroku
  api_key:
    secure: G4gdUhj4rF+yUS5rGTBYoNpkOzgsl7vObiBScQyAeffx2e1w7hVmk8y2cL+SzCqSprR1RF6bxoOYxVS8EVbwoPZS5AjVgYWGzJRvM62GDNzV5mcVwGjPWvtXsn9pc2208IEKQoe9S1yekJPBB8sGqY53Pg7nYuMAxs98dLw+qH55jpIfw+7Og3MmQ1rCTW+lrP+j0FDAo8PQBvQg/VqqnAdRbJ3Rw/94VXT22m3O47lLRg32s3+IMEx2FKDFwcil9viU8sw/6klRF+CqW2njfl6CTdtmH7k1EA6HoWKDAZ9ROvEUg3EdGIIBn70m52OArhSrMpKRLhHqCdcrsbT88kJV7A9p8C9RzlQ0CkOUZOnXNCBLuHOVNZUwLjqZfms0Fgrkf8i08F5pOSSmdByB0fnghXMeCftV67HGyOi0pK+2P+FZ6w5DdA0CW35fCwKp2HlSg1cfYNaLnKaplNNo0F5EQfkH+Wc/dLI4b7RFbEbwLtNCvG3DCkJghIel2qbCZ7vpkgc0MJXFYaxhMBLVVuLutloICpH08Gwjj/o2ghHMDIc7pXEsqcnBArasCqjFEAolA/odl2mrX5EOCuk5GImfcD8ZCiOsIZP97Wh+O1jX4oV8ZwyHbAbddtRxFn28BnSUOC3zcpcMTg57TaA/nfALO7Kc7mB7PkTz4JL9g9g=
  on:
    branches:
      only:
        - development
        
