env:
  global:
  - CC_TEST_REPORTER_ID=33722e59264a77494b85fbd0d0f1cec95321e83178937704265dc88015cca4de
rvm: 2.5.0
cache: bundler
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- bundle install && bin/rails db:create && bin/rails db:migrate && bundle exec rspec
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
services: "— postgresql"
deploy:
  provider: heroku
  api_key:
    secure: nmTThlgmabjg8pqvIiDbzAiPSzkSc3Uyqnc/61LqwJNsHUpIcTbqQWeWwyBOU+3QA0YnNSr0ps+YfKASscNA4sVIaAeFwlh4boFgbROV/TOEkE2lNnX3xQ5kp427wWyOiRKfpXR2vozOcv3JLZI8Zl4cJOm0i6J2dxVXDSctlP2e0WxovTNiLyi4sa6pnGi2cwsmu5gZQcgzjGbW6z3Lh1S4mqPJ09ozLd+K9lXDXNcN4zgyTYbZmhsiIoK2cZlHirymGk5OBlAwDHUvzqnWEqyCNaPFyHmpcaGPQYHg09Mnvmwoaf4bxFfWrFqpfIA8HUyy+aB3ybGWXowT7GGNG275zh3x0rXOq6DHqbO4/Z2gOJVumOFe5XzabGCq1955SQTAEwsAgqO5HenkS+oYUFxzlaJB+s7Y2I2IYbcGKShP8CsV2xV8an1WRXFn/4JQo1VcNwfSKvxi1v3psFO0pjQRPLaHIwr0iQ3Mt/B5an/LLRzXI2X5Msg6lF8bVqIPl1c4xQkIhkOrylNoaeYkxBy2mmbRy4XK+iNdCAoxEK/bVC3FrjYDPypUxxKuICDGwgvG7RPBY0kgcvcRsn1NCdAB4YUPdF22xsZPZcXvAzsr5sMmSskmtuHkKcCP+BEUX6zmDluy9/szYm8hbORysjAwXXiRB9122Q2rMepcGcU=
